import { Geist, Geist_Mono,Inter } from "next/font/google";
import { Amarante } from 'next/font/google';

import "./globals.css";
import NavigationBar from "@/components/Header/NavigationBar";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const amarante = Amarante({
  subsets: ['latin'],
  weight: '400', // Only one weight available
});

const inter = Inter({
  subsets: ['latin'],
  weight: '400', // Amarante has only 400
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={inter.className}
     
      >
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
